import type { Estado, Evento, Usuario } from "./tipos";
import { emDias } from "./formato";

const agora = () => new Date().toISOString();

export const usuariosDemo = (): Usuario[] => [
  {
    id: "u-visitante",
    nome: "Marina Vasconcelos",
    email: "visitante@feirafacil.com",
    senha: "123456",
    perfil: "visitante",
    telefone: "(82) 99999-1010",
    municipio: "Maceió",
    interesses: ["artesanato", "gastronomia"],
    notificacoes: { email: true, novidades: true, lembretes: false },
    status: "ativo",
    criadoEm: agora(),
    demo: true,
  },
  {
    id: "u-organizador",
    nome: "Cícero Tenório",
    email: "organizador@feirafacil.com",
    senha: "123456",
    perfil: "organizador",
    telefone: "(82) 98888-2020",
    municipio: "Maceió",
    interesses: ["artesanato", "economia-criativa"],
    notificacoes: { email: true, novidades: false, lembretes: true },
    status: "ativo",
    criadoEm: agora(),
    demo: true,
  },
  {
    id: "u-admin",
    nome: "Administração FeiraFácil",
    email: "admin@feirafacil.com",
    senha: "123456",
    perfil: "admin",
    municipio: "Maceió",
    interesses: [],
    notificacoes: { email: true, novidades: true, lembretes: true },
    status: "ativo",
    criadoEm: agora(),
    demo: true,
  },
  {
    id: "u-org2",
    nome: "Dandara Lima",
    email: "dandara@feirafacil.com",
    senha: "123456",
    perfil: "organizador",
    telefone: "(82) 97777-3030",
    municipio: "Penedo",
    interesses: ["cultura"],
    notificacoes: { email: true, novidades: true, lembretes: true },
    status: "ativo",
    criadoEm: agora(),
    demo: true,
  },
  {
    id: "u-vis2",
    nome: "Joaquim Barros",
    email: "joaquim@feirafacil.com",
    senha: "123456",
    perfil: "visitante",
    municipio: "Arapiraca",
    interesses: ["agricultura"],
    notificacoes: { email: false, novidades: true, lembretes: false },
    status: "ativo",
    criadoEm: agora(),
    demo: true,
  },
  {
    id: "u-vis3",
    nome: "Rafaela Cardoso",
    email: "rafaela@feirafacil.com",
    senha: "123456",
    perfil: "visitante",
    municipio: "Marechal Deodoro",
    interesses: ["moda", "cultura"],
    notificacoes: { email: true, novidades: false, lembretes: true },
    status: "suspenso",
    criadoEm: agora(),
    demo: true,
  },
];

export const eventosDemo = (): Evento[] => [
  {
    id: "e-pontal",
    nome: "Feira Criativa do Pontal",
    descricao:
      "Encontro demonstrativo de artesãs e artesãos com peças em bordado filé, cerâmica e palha, além de oficinas abertas ao público.",
    categoria: "artesanato",
    produtos: ["Bordado filé", "Cerâmica", "Peças em palha", "Oficinas"],
    data: emDias(4),
    horaInicio: "15:00",
    horaFim: "21:00",
    recorrencia: "semanal",
    municipio: "Maceió",
    bairro: "Pontal da Barra",
    endereco: "Praça demonstrativa do Pontal, s/n (endereço fictício)",
    referencia: "Próximo à orla da lagoa",
    lat: -9.700899,
    lng: -35.7787,
    entradaGratuita: true,
    acessibilidade: true,
    alimentacao: true,
    estacionamento: false,
    contato: "(82) 98888-2020",
    redeSocial: "@feiracriativapontal.demo",
    imagem: "artesanato",
    organizadorId: "u-organizador",
    status: "aprovado",
    patrocinado: true,
    patrocinioAte: emDias(20),
    visualizacoes: 1280,
    demo: true,
    criadoEm: agora(),
  },
  {
    id: "e-lagoa",
    nome: "Sabores da Lagoa",
    descricao:
      "Feira demonstrativa de gastronomia com cozinheiras locais, pratos à base de peixe e frutos da lagoa, doces e bebidas regionais.",
    categoria: "gastronomia",
    produtos: ["Comidas típicas", "Doces", "Sucos naturais", "Tapioca"],
    data: emDias(6),
    horaInicio: "17:00",
    horaFim: "22:00",
    recorrencia: "quinzenal",
    municipio: "Maceió",
    bairro: "Jaraguá",
    endereco: "Rua demonstrativa do Porto, 100 (endereço fictício)",
    referencia: "Em frente ao centro cultural",
    lat: -9.669,
    lng: -35.7305,
    entradaGratuita: true,
    acessibilidade: true,
    alimentacao: true,
    estacionamento: true,
    contato: "(82) 98888-2020",
    imagem: "gastronomia",
    organizadorId: "u-organizador",
    status: "aprovado",
    patrocinado: false,
    visualizacoes: 940,
    demo: true,
    criadoEm: agora(),
  },
  {
    id: "e-jaragua",
    nome: "Encontro de Artesãos de Jaraguá",
    descricao:
      "Roda de conversa e exposição demonstrativa de artesãos, com apresentação de técnicas tradicionais e venda direta.",
    categoria: "artesanato",
    produtos: ["Madeira", "Renda", "Bijuteria", "Quadros"],
    data: emDias(11),
    horaInicio: "16:00",
    horaFim: "22:00",
    recorrencia: "mensal",
    municipio: "Maceió",
    bairro: "Jaraguá",
    endereco: "Largo demonstrativo de Jaraguá, s/n (endereço fictício)",
    lat: -9.6659,
    lng: -35.7259,
    entradaGratuita: false,
    valorEntrada: "R$ 5,00 (simulado)",
    acessibilidade: false,
    alimentacao: true,
    estacionamento: false,
    imagem: "criativa",
    organizadorId: "u-organizador",
    status: "aprovado",
    patrocinado: false,
    visualizacoes: 610,
    demo: true,
    criadoEm: agora(),
  },
  {
    id: "e-pajucara",
    nome: "Feira de Moda Autoral da Pajuçara",
    descricao:
      "Mostra demonstrativa de marcas autorais alagoanas, brechós conscientes e acessórios feitos à mão.",
    categoria: "moda",
    produtos: ["Roupas autorais", "Brechó", "Chapéus", "Acessórios"],
    data: emDias(9),
    horaInicio: "14:00",
    horaFim: "20:00",
    recorrencia: "mensal",
    municipio: "Maceió",
    bairro: "Pajuçara",
    endereco: "Avenida demonstrativa da orla, 500 (endereço fictício)",
    lat: -9.6689,
    lng: -35.7096,
    entradaGratuita: true,
    acessibilidade: true,
    alimentacao: false,
    estacionamento: true,
    imagem: "moda",
    organizadorId: "u-org2",
    status: "aprovado",
    patrocinado: true,
    patrocinioAte: emDias(15),
    visualizacoes: 720,
    demo: true,
    criadoEm: agora(),
  },
  {
    id: "e-agricultura",
    nome: "Feira da Agricultura Familiar",
    descricao:
      "Feira demonstrativa de produtores familiares com hortaliças, raízes, mel e polpas de frutas da região.",
    categoria: "agricultura",
    produtos: ["Hortaliças", "Mel", "Polpas", "Macaxeira"],
    data: emDias(3),
    horaInicio: "06:00",
    horaFim: "12:00",
    recorrencia: "semanal",
    municipio: "Arapiraca",
    bairro: "Centro",
    endereco: "Pátio demonstrativo do Centro, s/n (endereço fictício)",
    lat: -9.7524,
    lng: -36.6611,
    entradaGratuita: true,
    acessibilidade: true,
    alimentacao: true,
    estacionamento: true,
    imagem: "agricultura",
    organizadorId: "u-org2",
    status: "aprovado",
    patrocinado: false,
    visualizacoes: 430,
    demo: true,
    criadoEm: agora(),
  },
  {
    id: "e-marechal",
    nome: "Arte e Cultura em Marechal Deodoro",
    descricao:
      "Programação cultural demonstrativa com música, dança e barracas de arte no centro histórico.",
    categoria: "cultura",
    produtos: ["Música ao vivo", "Dança", "Arte popular", "Comidas"],
    data: emDias(14),
    horaInicio: "17:00",
    horaFim: "23:00",
    recorrencia: "mensal",
    municipio: "Marechal Deodoro",
    bairro: "Centro Histórico",
    endereco: "Praça demonstrativa do Centro Histórico (endereço fictício)",
    lat: -9.7096,
    lng: -35.8952,
    entradaGratuita: true,
    acessibilidade: false,
    alimentacao: true,
    estacionamento: false,
    imagem: "cultura",
    organizadorId: "u-org2",
    status: "aprovado",
    patrocinado: false,
    visualizacoes: 880,
    demo: true,
    criadoEm: agora(),
  },
  {
    id: "e-penedo",
    nome: "Encontro Criativo de Penedo",
    descricao:
      "Encontro demonstrativo de economia criativa às margens do Rio São Francisco, com design, ilustração e editorial independente.",
    categoria: "economia-criativa",
    produtos: ["Ilustração", "Zines", "Design", "Cerâmica"],
    data: emDias(18),
    horaInicio: "15:00",
    horaFim: "21:00",
    recorrencia: "unico",
    municipio: "Penedo",
    bairro: "Centro",
    endereco: "Rua demonstrativa da Aurora, 42 (endereço fictício)",
    lat: -10.2905,
    lng: -36.5862,
    entradaGratuita: false,
    valorEntrada: "R$ 10,00 (simulado)",
    acessibilidade: true,
    alimentacao: true,
    estacionamento: true,
    imagem: "criativa",
    organizadorId: "u-org2",
    status: "pendente",
    patrocinado: false,
    visualizacoes: 210,
    demo: true,
    criadoEm: agora(),
  },
  {
    id: "e-jatiuca",
    nome: "Feira de Economia Criativa da Jatiúca",
    descricao:
      "Feira demonstrativa com empreendedores criativos, food trucks e programação musical no fim de tarde.",
    categoria: "economia-criativa",
    produtos: ["Papelaria", "Joias", "Food trucks", "Serigrafia"],
    data: emDias(7),
    horaInicio: "16:00",
    horaFim: "22:00",
    recorrencia: "quinzenal",
    municipio: "Maceió",
    bairro: "Jatiúca",
    endereco: "Praça demonstrativa da Jatiúca, s/n (endereço fictício)",
    lat: -9.6486,
    lng: -35.7,
    entradaGratuita: true,
    acessibilidade: true,
    alimentacao: true,
    estacionamento: true,
    imagem: "criativa",
    organizadorId: "u-organizador",
    status: "aprovado",
    patrocinado: false,
    visualizacoes: 1020,
    demo: true,
    criadoEm: agora(),
  },
  {
    id: "e-barra",
    nome: "Feira de Sabores da Barra de São Miguel",
    descricao:
      "Feira demonstrativa de gastronomia litorânea com produtores locais e oficinas de culinária.",
    categoria: "gastronomia",
    produtos: ["Frutos do mar", "Água de coco", "Doces", "Oficinas"],
    data: emDias(21),
    horaInicio: "11:00",
    horaFim: "18:00",
    recorrencia: "mensal",
    municipio: "Barra de São Miguel",
    bairro: "Centro",
    endereco: "Orla demonstrativa, s/n (endereço fictício)",
    lat: -9.8386,
    lng: -35.9058,
    entradaGratuita: true,
    acessibilidade: true,
    alimentacao: true,
    estacionamento: true,
    imagem: "gastronomia",
    organizadorId: "u-organizador",
    status: "aprovado",
    patrocinado: false,
    visualizacoes: 360,
    demo: true,
    criadoEm: agora(),
  },
];

export const estadoInicial = (): Estado => {
  const eventos = eventosDemo();
  const criado = new Date();
  const iso = (dias: number) =>
    new Date(criado.getTime() - dias * 86400000).toISOString();

  return {
    versao: 1,
    usuarios: usuariosDemo(),
    eventos,
    avaliacoes: [
      {
        id: "a-1",
        eventoId: "e-pontal",
        autorId: "u-vis2",
        autorNome: "Joaquim Barros",
        nota: 5,
        comentario:
          "Ambiente muito agradável e peças lindas. Achei fácil de chegar e de circular.",
        criadoEm: iso(3),
        oculto: false,
      },
      {
        id: "a-2",
        eventoId: "e-pontal",
        autorId: "u-vis3",
        autorNome: "Rafaela Cardoso",
        nota: 4,
        comentario: "Gostei bastante, só senti falta de mais opções de bebida.",
        criadoEm: iso(6),
        oculto: false,
      },
      {
        id: "a-3",
        eventoId: "e-lagoa",
        autorId: "u-vis2",
        autorNome: "Joaquim Barros",
        nota: 5,
        comentario: "Comida excelente e preço justo.",
        criadoEm: iso(2),
        oculto: false,
      },
      {
        id: "a-4",
        eventoId: "e-jatiuca",
        autorId: "u-vis3",
        autorNome: "Rafaela Cardoso",
        nota: 3,
        comentario: "Bacana, mas estava cheio demais no início da noite.",
        criadoEm: iso(8),
        oculto: false,
      },
      {
        id: "a-5",
        eventoId: "e-marechal",
        autorId: "u-vis2",
        autorNome: "Joaquim Barros",
        nota: 4,
        comentario: "A programação cultural valeu muito a pena.",
        criadoEm: iso(10),
        oculto: false,
      },
      {
        id: "a-6",
        eventoId: "e-pajucara",
        autorId: "u-vis3",
        autorNome: "Rafaela Cardoso",
        nota: 2,
        comentario: "Comentário demonstrativo com tom agressivo, usado para testar a moderação.",
        criadoEm: iso(1),
        oculto: false,
      },
    ],
    denuncias: [
      {
        id: "d-1",
        avaliacaoId: "a-6",
        eventoId: "e-pajucara",
        motivo: "Linguagem ofensiva",
        autorId: "u-vis2",
        criadoEm: iso(1),
        situacao: "aberta",
      },
    ],
    atividades: [
      {
        id: "at-1",
        tipo: "evento",
        descricao: "Evento demonstrativo “Feira Criativa do Pontal” criado.",
        criadoEm: iso(12),
        autor: "Cícero Tenório",
      },
      {
        id: "at-2",
        tipo: "avaliacao",
        descricao: "Nova avaliação publicada em “Sabores da Lagoa”.",
        criadoEm: iso(2),
        autor: "Joaquim Barros",
      },
      {
        id: "at-3",
        tipo: "denuncia",
        descricao: "Comentário denunciado em “Feira de Moda Autoral da Pajuçara”.",
        criadoEm: iso(1),
        autor: "Joaquim Barros",
      },
      {
        id: "at-4",
        tipo: "patrocinio",
        descricao: "Destaque patrocinado simulado ativado para “Feira Criativa do Pontal”.",
        criadoEm: iso(5),
        autor: "Cícero Tenório",
      },
    ],
    feedbacks: [
      {
        id: "f-1",
        autorId: "u-organizador",
        tipo: "sugestao",
        nota: 4,
        mensagem: "Seria útil poder duplicar um evento recorrente.",
        criadoEm: iso(4),
      },
    ],
    favoritos: {
      "u-visitante": ["e-pontal", "e-lagoa"],
      "u-vis2": ["e-agricultura"],
    },
    agenda: {
      "u-visitante": ["e-pontal"],
    },
    sessaoId: null,
  };
};
