import { createFileRoute, Link, notFound, useNavigate } from "@tanstack/react-router";
import { CalendarPlus, Check, Clock, ExternalLink, Heart, MapPin, Share2, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import { LayoutPublico } from "@/components/layout-publico";
import { EventoCard } from "@/components/evento-card";
import { Container } from "@/components/pagina";
import { Botao } from "@/components/ui/botao";
import { AreaTexto } from "@/components/ui/campo";
import { Estrelas } from "@/components/ui/estrelas";
import { imagemDe, nomeCategoria } from "@/lib/catalogo";
import { formatarData, formatarDataHora, formatarHorario } from "@/lib/formato";
import { alternarAgenda, alternarFavorito, avaliacoesVisiveis, denunciar, excluirAvaliacao, notaMedia, salvarAvaliacao, useEstado, useUsuario } from "@/lib/loja";

export const Route = createFileRoute("/feirinhas/$id")({
  head: () => ({ meta: [{ title: "Detalhes da feirinha — FeiraFácil Alagoas" }, { name:"description", content:"Informações, localização e avaliações de uma feirinha em Alagoas." }, { property:"og:title",content:"Detalhes da feirinha — FeiraFácil Alagoas"},{property:"og:description",content:"Confira data, local, produtos e avaliações."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: Detalhes,
});
function Detalhes(){
  const {id}=Route.useParams(); const estado=useEstado(); const usuario=useUsuario(); const navigate=useNavigate(); const evento=estado.eventos.find(e=>e.id===id);
  const [nota,setNota]=useState(5); const [texto,setTexto]=useState(""); const [aviso,setAviso]=useState("");
  if(!evento) throw notFound();
  const avaliacoes=avaliacoesVisiveis(estado,id); const minha=usuario?estado.avaliacoes.find(a=>a.eventoId===id&&a.autorId===usuario.id):undefined; const favorito=usuario?(estado.favoritos[usuario.id]??[]).includes(id):false; const naAgenda=usuario?(estado.agenda[usuario.id]??[]).includes(id):false;
  const exigirLogin=(acao:()=>void)=>{if(!usuario){void navigate({to:"/login",search:{voltar:`/feirinhas/${id}`}});return;}acao();};
  const compartilhar=async()=>{try{await navigator.clipboard.writeText(window.location.href);setAviso("Link copiado!");}catch{setAviso("Não foi possível copiar o link.");}setTimeout(()=>setAviso(""),2500);};
  const publicar=()=>{if(!usuario)return void navigate({to:"/login",search:{voltar:`/feirinhas/${id}`}}); if(!texto.trim())return; salvarAvaliacao({id:minha?.id??`a-${Date.now()}`,eventoId:id,autorId:usuario.id,autorNome:usuario.nome,nota,comentario:texto,criadoEm:new Date().toISOString(),oculto:false,...(minha?.resposta?{resposta:minha.resposta}:{})});setTexto("");setAviso(minha?"Avaliação atualizada.":"Avaliação publicada.");};
  const relacionados=estado.eventos.filter(e=>e.id!==id&&e.status==="aprovado"&&(e.categoria===evento.categoria||e.municipio===evento.municipio)).slice(0,3);
  return <LayoutPublico><section className="bg-marinho text-marinho-foreground"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[1fr_1.1fr] lg:px-8"><div className="flex flex-col justify-center"><div className="flex flex-wrap gap-2"><span className="rounded-sm bg-primary px-2 py-1 text-xs font-bold">{nomeCategoria(evento.categoria)}</span>{evento.demo&&<span className="rounded-sm bg-card/15 px-2 py-1 text-xs font-bold">Evento demonstrativo</span>}{evento.patrocinado&&<span className="rounded-sm bg-aviso px-2 py-1 text-xs font-bold text-marinho">Patrocinado</span>}</div><h1 className="mt-4 text-4xl font-bold leading-tight sm:text-5xl">{evento.nome}</h1><p className="mt-4 text-lg text-marinho-foreground/80">{evento.descricao}</p><div className="mt-6 flex items-center gap-3"><Estrelas nota={Math.round(notaMedia(estado,id))}/><strong>{notaMedia(estado,id)||"Novo"}</strong><span className="text-sm opacity-70">({avaliacoes.length} avaliações)</span></div></div><img src={imagemDe(evento.imagem)} width={1200} height={800} alt={`Ilustração temática de ${evento.nome}`} className="aspect-[16/10] w-full rounded-lg object-cover shadow-2xl"/></div></section>
  <Container><div className="grid gap-8 lg:grid-cols-[1fr_340px]"><div><div className="grid gap-4 sm:grid-cols-2"><Info icon={<Clock/>} titulo="Data e horário" texto={`${formatarData(evento.data)} · ${formatarHorario(evento.horaInicio,evento.horaFim)}`}/><Info icon={<MapPin/>} titulo="Local" texto={`${evento.bairro}, ${evento.municipio}`}/></div><section className="mt-8"><h2 className="text-2xl font-bold text-marinho">Sobre a feirinha</h2><p className="mt-3 leading-relaxed text-muted-foreground">{evento.descricao}</p><h3 className="mt-6 font-bold">Produtos e serviços</h3><div className="mt-3 flex flex-wrap gap-2">{evento.produtos.map(p=><span key={p} className="rounded-sm bg-areia px-3 py-1.5 text-sm font-medium">{p}</span>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2">{[`${evento.entradaGratuita?"Entrada gratuita":evento.valorEntrada}`,evento.acessibilidade?"Local com acessibilidade":"Acessibilidade não informada",evento.alimentacao?"Alimentação no local":"Sem alimentação informada",evento.estacionamento?"Estacionamento disponível":"Sem estacionamento informado"].map(t=><span key={t} className="flex items-center gap-2 text-sm"><Check className="size-4 text-sucesso"/>{t}</span>)}</div></section>
  <section className="mt-10"><h2 className="text-2xl font-bold text-marinho">Avaliações e comentários</h2><div className="mt-5 rounded-lg border bg-card p-5"><h3 className="font-bold">{minha?"Editar sua avaliação":"Conte como foi sua experiência"}</h3>{usuario?.perfil==="visitante"?<><div className="mt-3"><Estrelas nota={nota} tamanho="lg" interativo aoMudar={setNota}/></div><AreaTexto className="mt-3" placeholder={minha?.comentario??"Escreva sua avaliação..."} value={texto} onChange={e=>setTexto(e.target.value)}/><div className="mt-3 flex gap-2"><Botao onClick={publicar}>{minha?"Atualizar":"Publicar avaliação"}</Botao>{minha&&<Botao variant="danger" onClick={()=>excluirAvaliacao(minha.id,usuario.nome)}><Trash2 className="size-4"/>Excluir</Botao>}</div></>:<><p className="mt-2 text-sm text-muted-foreground">Entre como visitante para avaliar e comentar.</p><Botao className="mt-3" asChild><Link to="/login" search={{voltar:`/feirinhas/${id}`}}>Entrar para avaliar</Link></Botao></>}</div><div className="mt-5 grid gap-4">{avaliacoes.map(a=><article key={a.id} className="rounded-lg border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><strong>{a.autorNome}</strong><div className="mt-1"><Estrelas nota={a.nota}/></div></div><time className="text-xs text-muted-foreground">{formatarDataHora(a.criadoEm)}</time></div><p className="mt-3 text-sm leading-relaxed">{a.comentario}</p>{a.resposta&&<div className="mt-3 rounded-md bg-muted p-3 text-sm"><strong>Resposta do organizador</strong><p className="mt-1">{a.resposta.texto}</p></div>}{usuario&&usuario.id!==a.autorId&&<button className="mt-3 text-xs font-bold text-muted-foreground hover:text-destructive" onClick={()=>denunciar(a.id,id,"Conteúdo inadequado",usuario.id,usuario.nome)}>Denunciar comentário</button>}</article>)}</div></section></div>
  <aside><div className="sticky top-24 rounded-lg border bg-card p-5 shadow-[var(--shadow-soft)]"><h2 className="font-bold text-marinho">Planeje sua visita</h2><p className="mt-3 text-sm"><strong>{evento.endereco}</strong></p>{evento.referencia&&<p className="mt-1 text-sm text-muted-foreground">{evento.referencia}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><Botao variant={favorito?"primary":"outline"} onClick={()=>exigirLogin(()=>alternarFavorito(usuario?.id??"",id))}><Heart className={`size-4 ${favorito?"fill-current":""}`}/>{favorito?"Favoritado":"Favoritar"}</Botao><Botao variant="outline" onClick={compartilhar}><Share2 className="size-4"/>Compartilhar</Botao><Botao variant="outline" asChild><a target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${evento.lat}&mlon=${evento.lng}#map=16/${evento.lat}/${evento.lng}`}><ExternalLink className="size-4"/>Como chegar</a></Botao><Botao variant={naAgenda?"primary":"outline"} onClick={()=>exigirLogin(()=>alternarAgenda(usuario?.id??"",id))}><CalendarPlus className="size-4"/>{naAgenda?"Na agenda":"Minha agenda"}</Botao></div>{aviso&&<p role="status" className="mt-3 rounded bg-muted p-2 text-center text-sm font-bold text-sucesso">{aviso}</p>}<div className="mt-5 border-t pt-4 text-sm"><p className="font-bold">Organizador</p><p className="text-muted-foreground">{estado.usuarios.find(u=>u.id===evento.organizadorId)?.nome??"Organizador demonstrativo"}</p><p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4"/>Dados deste evento são demonstrativos.</p></div></div></aside></div>
  {relacionados.length>0&&<section className="mt-14"><h2 className="text-2xl font-bold text-marinho">Você também pode gostar</h2><div className="mt-5 grid gap-5 md:grid-cols-3">{relacionados.map(e=><EventoCard key={e.id} evento={e}/>)}</div></section>}</Container></LayoutPublico>;
}
function Info({icon,titulo,texto}:{icon:React.ReactNode;titulo:string;texto:string}){return <div className="flex gap-3 rounded-lg border bg-card p-4"><span className="text-primary [&>svg]:size-5">{icon}</span><div><p className="text-sm font-bold">{titulo}</p><p className="mt-1 text-sm text-muted-foreground">{texto}</p></div></div>}
