import { Link, useRouterState } from "@tanstack/react-router";
import { CalendarDays, ClipboardList, Home, LogOut, Menu, MessageSquare, PlusCircle, Send, ShieldCheck, Star, Store, Users, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Logo } from "./logo"; import { Botao } from "./ui/botao"; import { sair, useUsuario } from "@/lib/loja";
const org=[{to:"/organizador" as const,label:"Visão geral",icon:Home},{to:"/organizador/eventos" as const,label:"Meus eventos",icon:CalendarDays},{to:"/organizador/eventos/novo" as const,label:"Novo evento",icon:PlusCircle},{to:"/organizador/avaliacoes" as const,label:"Avaliações",icon:Star},{to:"/organizador/feedback" as const,label:"Feedback",icon:Send}];
const adm=[{to:"/admin" as const,label:"Visão geral",icon:Home},{to:"/admin/eventos" as const,label:"Eventos",icon:CalendarDays},{to:"/admin/usuarios" as const,label:"Usuários",icon:Users},{to:"/admin/moderacao" as const,label:"Moderação",icon:MessageSquare},{to:"/admin/atividades" as const,label:"Atividades",icon:ClipboardList}];
export function PainelLayout({tipo,children}:{tipo:"organizador"|"admin";children:ReactNode}){const usuario=useUsuario(),[menu,setMenu]=useState(false);const caminho=useRouterState({select:s=>s.location.pathname});const links=tipo==="admin"?adm:org;if(!usuario||usuario.perfil!==tipo)return <div className="grid min-h-screen place-items-center bg-background px-4"><div className="max-w-md text-center"><ShieldCheck className="mx-auto size-12 text-primary"/><h1 className="mt-4 text-3xl font-bold text-marinho">Área restrita</h1><p className="mt-2 text-muted-foreground">Entre com um perfil de {tipo} para acessar esta área.</p><Botao className="mt-5" asChild><Link to="/login" search={{voltar:caminho}}>Entrar</Link></Botao></div></div>;return <div className="min-h-screen bg-background lg:grid lg:grid-cols-[250px_1fr]"><aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-sidebar p-4 text-sidebar-foreground transition lg:sticky lg:top-0 lg:block lg:h-screen ${menu?"block":"hidden"}`}><div className="flex items-center justify-between"><div className="rounded-md bg-card p-2"><Logo/></div><button className="lg:hidden" onClick={()=>setMenu(false)}><X/></button></div><div className="mt-6 border-b border-sidebar-border pb-4"><p className="text-xs uppercase opacity-60">{tipo}</p><strong className="mt-1 block">{usuario.nome}</strong></div><nav className="mt-5 grid gap-1">{links.map(l=><Link key={l.to} to={l.to} activeOptions={{exact:l.to==="/admin"||l.to==="/organizador"}} onClick={()=>setMenu(false)} activeProps={{className:"bg-sidebar-primary text-sidebar-primary-foreground"}} className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-bold hover:bg-sidebar-accent"><l.icon className="size-4"/>{l.label}</Link>)}</nav><div className="absolute bottom-4 left-4 right-4 grid gap-1"><Link to="/" className="flex items-center gap-2 rounded px-3 py-2 text-sm hover:bg-sidebar-accent"><Store className="size-4"/>Ver site público</Link><button onClick={sair} className="flex items-center gap-2 rounded px-3 py-2 text-sm hover:bg-sidebar-accent"><LogOut className="size-4"/>Sair</button></div></aside><div className="min-w-0"><header className="flex h-16 items-center justify-between border-b bg-card px-4 sm:px-6"><button className="lg:hidden" onClick={()=>setMenu(true)} aria-label="Abrir menu"><Menu/></button><strong className="font-display text-lg text-marinho">Painel {tipo==="admin"?"administrativo":"do organizador"}</strong><span className="text-sm text-muted-foreground">{usuario.nome.split(" ")[0]}</span></header><main className="p-4 sm:p-6 lg:p-8">{children}</main></div></div>}
export function TituloPainel({titulo,descricao,acao}:{titulo:string;descricao?:string;acao?:ReactNode}){return <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold text-marinho">{titulo}</h1>{descricao&&<p className="mt-1 text-sm text-muted-foreground">{descricao}</p>}</div>{acao}</div>}
export function Metrica({rotulo,valor,detalhe,icon}:{rotulo:string;valor:string|number;detalhe?:string;icon:ReactNode}){return <div className="rounded-lg border bg-card p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-muted-foreground">{rotulo}</p><strong className="mt-2 block text-3xl text-marinho">{valor}</strong>{detalhe&&<p className="mt-1 text-xs text-muted-foreground">{detalhe}</p>}</div><span className="grid size-10 place-items-center rounded-md bg-areia text-primary [&>svg]:size-5">{icon}</span></div></div>}
