/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as FeirinhasRouteImport } from './routes/feirinhas'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as FeirinhasIndexRouteImport } from './routes/feirinhas.index'
import { Route as FeirinhasIdRouteImport } from './routes/feirinhas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const FeirinhasRoute = FeirinhasRouteImport.update({
  id: '/feirinhas',
  path: '/feirinhas',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const FeirinhasIndexRoute = FeirinhasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeirinhasRoute,
} as any)
const FeirinhasIdRoute = FeirinhasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FeirinhasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/creditos': typeof CreditosRoute
  '/feirinhas': typeof FeirinhasRouteWithChildren
  '/mapa': typeof MapaRoute
  '/feirinhas/$id': typeof FeirinhasIdRoute
  '/feirinhas/': typeof FeirinhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/creditos': typeof CreditosRoute
  '/mapa': typeof MapaRoute
  '/feirinhas/$id': typeof FeirinhasIdRoute
  '/feirinhas': typeof FeirinhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/creditos': typeof CreditosRoute
  '/feirinhas': typeof FeirinhasRouteWithChildren
  '/mapa': typeof MapaRoute
  '/feirinhas/$id': typeof FeirinhasIdRoute
  '/feirinhas/': typeof FeirinhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/como-funciona'
    | '/creditos'
    | '/feirinhas'
    | '/mapa'
    | '/feirinhas/$id'
    | '/feirinhas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/como-funciona'
    | '/creditos'
    | '/mapa'
    | '/feirinhas/$id'
    | '/feirinhas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/como-funciona'
    | '/creditos'
    | '/feirinhas'
    | '/mapa'
    | '/feirinhas/$id'
    | '/feirinhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CreditosRoute: typeof CreditosRoute
  FeirinhasRoute: typeof FeirinhasRouteWithChildren
  MapaRoute: typeof MapaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feirinhas': {
      id: '/feirinhas'
      path: '/feirinhas'
      fullPath: '/feirinhas'
      preLoaderRoute: typeof FeirinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feirinhas/': {
      id: '/feirinhas/'
      path: '/'
      fullPath: '/feirinhas/'
      preLoaderRoute: typeof FeirinhasIndexRouteImport
      parentRoute: typeof FeirinhasRoute
    }
    '/feirinhas/$id': {
      id: '/feirinhas/$id'
      path: '/$id'
      fullPath: '/feirinhas/$id'
      preLoaderRoute: typeof FeirinhasIdRouteImport
      parentRoute: typeof FeirinhasRoute
    }
  }
}

interface FeirinhasRouteChildren {
  FeirinhasIdRoute: typeof FeirinhasIdRoute
  FeirinhasIndexRoute: typeof FeirinhasIndexRoute
}

const FeirinhasRouteChildren: FeirinhasRouteChildren = {
  FeirinhasIdRoute: FeirinhasIdRoute,
  FeirinhasIndexRoute: FeirinhasIndexRoute,
}

const FeirinhasRouteWithChildren = FeirinhasRoute._addFileChildren(
  FeirinhasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CreditosRoute: CreditosRoute,
  FeirinhasRoute: FeirinhasRouteWithChildren,
  MapaRoute: MapaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
