/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FeirinhasRouteImport } from './routes/feirinhas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as OrganizadorRouteImport } from './routes/organizador'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as FeirinhasIndexRouteImport } from './routes/feirinhas.index'
import { Route as FeirinhasIdRouteImport } from './routes/feirinhas.$id'
import { Route as OrganizadorEventosRouteImport } from './routes/organizador.eventos'
import { Route as OrganizadorEventosIndexRouteImport } from './routes/organizador.eventos.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FeirinhasRoute = FeirinhasRouteImport.update({
  id: '/feirinhas',
  path: '/feirinhas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorRoute = OrganizadorRouteImport.update({
  id: '/organizador',
  path: '/organizador',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FeirinhasIndexRoute = FeirinhasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeirinhasRoute,
} as any)
const FeirinhasIdRoute = FeirinhasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FeirinhasRoute,
} as any)
const OrganizadorEventosRoute = OrganizadorEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => OrganizadorRoute,
} as any)
const OrganizadorEventosIndexRoute = OrganizadorEventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizadorEventosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/creditos': typeof CreditosRoute
  '/favoritos': typeof FavoritosRoute
  '/feirinhas': typeof FeirinhasRouteWithChildren
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/organizador': typeof OrganizadorRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/feirinhas/$id': typeof FeirinhasIdRoute
  '/organizador/eventos': typeof OrganizadorEventosRouteWithChildren
  '/feirinhas/': typeof FeirinhasIndexRoute
  '/organizador/eventos/': typeof OrganizadorEventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/creditos': typeof CreditosRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/organizador': typeof OrganizadorRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/feirinhas/$id': typeof FeirinhasIdRoute
  '/feirinhas': typeof FeirinhasIndexRoute
  '/organizador/eventos': typeof OrganizadorEventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/creditos': typeof CreditosRoute
  '/favoritos': typeof FavoritosRoute
  '/feirinhas': typeof FeirinhasRouteWithChildren
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/organizador': typeof OrganizadorRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/feirinhas/$id': typeof FeirinhasIdRoute
  '/organizador/eventos': typeof OrganizadorEventosRouteWithChildren
  '/feirinhas/': typeof FeirinhasIndexRoute
  '/organizador/eventos/': typeof OrganizadorEventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/como-funciona'
    | '/creditos'
    | '/favoritos'
    | '/feirinhas'
    | '/login'
    | '/mapa'
    | '/organizador'
    | '/perfil'
    | '/feirinhas/$id'
    | '/organizador/eventos'
    | '/feirinhas/'
    | '/organizador/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/como-funciona'
    | '/creditos'
    | '/favoritos'
    | '/login'
    | '/mapa'
    | '/organizador'
    | '/perfil'
    | '/feirinhas/$id'
    | '/feirinhas'
    | '/organizador/eventos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/como-funciona'
    | '/creditos'
    | '/favoritos'
    | '/feirinhas'
    | '/login'
    | '/mapa'
    | '/organizador'
    | '/perfil'
    | '/feirinhas/$id'
    | '/organizador/eventos'
    | '/feirinhas/'
    | '/organizador/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CreditosRoute: typeof CreditosRoute
  FavoritosRoute: typeof FavoritosRoute
  FeirinhasRoute: typeof FeirinhasRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  OrganizadorRoute: typeof OrganizadorRouteWithChildren
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feirinhas': {
      id: '/feirinhas'
      path: '/feirinhas'
      fullPath: '/feirinhas'
      preLoaderRoute: typeof FeirinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador': {
      id: '/organizador'
      path: '/organizador'
      fullPath: '/organizador'
      preLoaderRoute: typeof OrganizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feirinhas/': {
      id: '/feirinhas/'
      path: '/'
      fullPath: '/feirinhas/'
      preLoaderRoute: typeof FeirinhasIndexRouteImport
      parentRoute: typeof FeirinhasRoute
    }
    '/feirinhas/$id': {
      id: '/feirinhas/$id'
      path: '/$id'
      fullPath: '/feirinhas/$id'
      preLoaderRoute: typeof FeirinhasIdRouteImport
      parentRoute: typeof FeirinhasRoute
    }
    '/organizador/eventos': {
      id: '/organizador/eventos'
      path: '/eventos'
      fullPath: '/organizador/eventos'
      preLoaderRoute: typeof OrganizadorEventosRouteImport
      parentRoute: typeof OrganizadorRoute
    }
    '/organizador/eventos/': {
      id: '/organizador/eventos/'
      path: '/'
      fullPath: '/organizador/eventos/'
      preLoaderRoute: typeof OrganizadorEventosIndexRouteImport
      parentRoute: typeof OrganizadorEventosRoute
    }
  }
}

interface FeirinhasRouteChildren {
  FeirinhasIdRoute: typeof FeirinhasIdRoute
  FeirinhasIndexRoute: typeof FeirinhasIndexRoute
}

const FeirinhasRouteChildren: FeirinhasRouteChildren = {
  FeirinhasIdRoute: FeirinhasIdRoute,
  FeirinhasIndexRoute: FeirinhasIndexRoute,
}

const FeirinhasRouteWithChildren = FeirinhasRoute._addFileChildren(
  FeirinhasRouteChildren,
)

interface OrganizadorEventosRouteChildren {
  OrganizadorEventosIndexRoute: typeof OrganizadorEventosIndexRoute
}

const OrganizadorEventosRouteChildren: OrganizadorEventosRouteChildren = {
  OrganizadorEventosIndexRoute: OrganizadorEventosIndexRoute,
}

const OrganizadorEventosRouteWithChildren =
  OrganizadorEventosRoute._addFileChildren(OrganizadorEventosRouteChildren)

interface OrganizadorRouteChildren {
  OrganizadorEventosRoute: typeof OrganizadorEventosRouteWithChildren
}

const OrganizadorRouteChildren: OrganizadorRouteChildren = {
  OrganizadorEventosRoute: OrganizadorEventosRouteWithChildren,
}

const OrganizadorRouteWithChildren = OrganizadorRoute._addFileChildren(
  OrganizadorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CreditosRoute: CreditosRoute,
  FavoritosRoute: FavoritosRoute,
  FeirinhasRoute: FeirinhasRouteWithChildren,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  OrganizadorRoute: OrganizadorRouteWithChildren,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
